services:
  sample-onchain-test:
    image: ghcr.io/exh0115/sample-onchain-test:v1
    container_name: sample-onchain-test
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - /data/workload/secrets/env
    # environment:
    #   AUTH_CONTRACT_ADDR: "0x0000000000000000000000000000000000000000"
